SUMMARY = "Ka-Ro userfs Image"
LICENSE = "MIT"

require karo-subimage.inc

IMAGE_FSTYPES = "ext4 tar.bz2"

IMAGE_NAME_SUFFIX = ".${STM32MP_USERFS_LABEL}"

IMAGE_PARTITION_MOUNTPOINT = "${STM32MP_USERFS_MOUNTPOINT_IMAGE}"

IMAGE_ROOTFS_MAXSIZE = "${USERFS_PARTITION_SIZE}"
IMAGE_ROOTFS_SIZE = "${USERFS_PARTITION_SIZE}"
